apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-data
  labels:
    name: www-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: csi-simplenfs-flexdriver
    volumeHandle: data-id
    volumeAttributes:
      server: 172.16.0.25
      share: dws_nas_scratch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["www-data"]
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: www-data
  volumes:
  - name: www-data
    persistentVolumeClaim:
      claimName: www-data
